name: ci
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Lint code
        run: pnpm lint

      - name: Run tests
        run: pnpm test

